### ISSUE TITLE
是否可以将其应用于windows系统

### ISSUE THREAD

**Issue by DylanLN** [zdzhaoyong/svar_rosbridge#1]
你好，我想问一下能否将其用于windows且未安装ros的系统中呢

**Comment by zdzhaoyong** [comment]
The code does not rely on ROS and should able to be compiled in windows system, but the boost related denpendency should be solved.

**Comment by ROMOCN** [comment]
这是一个很好的项目，可以快速开发在非ros与ros交互，但是遇到一些问题
win下如何解决boost 的依赖问题，我想订阅sensor_msgs/Image ，但是rosbradge_server 显示

```
[rosbridge_websocket]: Exception calling subscribe callback: 'Image' object has no attribute '_slot_types'
```
同时我使用Python的svar，win下安装失败，报错如下
```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\romow\AppData\Local\Temp\pip-install-xbnms4gi\svar_043c9030a9a94de5aa9831862c227bc7\setup.py", line 60, in <module>
          setup(
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "D:\AllLib\C++ROS\noob_test\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\romow\AppData\Local\Temp\pip-install-xbnms4gi\svar_043c9030a9a94de5aa9831862c227bc7\setup.py", line 32, in run
          self.build_extension(ext)
        File "C:\Users\romow\AppData\Local\Temp\pip-install-xbnms4gi\svar_043c9030a9a94de5aa9831862c227bc7\setup.py", line 58, in build_extension
          subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
      cmake C:\Users\romow\AppData\Local\Temp\pip-install-xbnms4gi\svar_043c9030a9a94de5aa9831862c227bc7/src/python/svarpy ['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\romow\\AppData\\Local\\Temp\\pip-install-xbnms4gi\\svar_043c903
0a9a94de5aa9831862c227bc7\\build\\lib.win-amd64-3.10', '-DPYTHON_EXECUTABLE=D:\\AllLib\\C++ROS\\noob_test\\venv\\Scripts\\python.exe', '-DPIPING=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\romow\\AppData\\Local\\Temp\\
pip-install-xbnms4gi\\svar_043c9030a9a94de5aa9831862c227bc7\\build\\lib.win-amd64-3.10', '-A', 'x64']
```
linux下运行时显示段错误，log显示，在下面这里失败，打印段错误
```
ros=svar.load('svar_rosbridge')
```
